import csv

class EnergyProductionAPI:
    
    def __init__(self, filename):
            
        with open(filename, newline='') as energyFile:
            self.energy_production = list(csv.DictReader(energyFile))
            
    
    """
    Equivalence Classes:
        -Valid state
            -Input: Alabama, ... , Wyoming
        
        -Not a valid state but still a string
            -Input: Ontario
        
        -Not a string:
            -Input: 10
        
    """
    def isolateDatasetByState(state):
        """
            Prunes the working dataset down by the given State (ie. only Wisconsin's data)

            Retrieves all columns in the current working data set containing the given State, 
            regardless of category of production.

            Args:
                state: a string containing the specified state in written format

            Returns:
                A list of data that contains all of the cells that correspond to the specified state.
        """

        print("The database has be paired down to only include", state)

        return 0

    """
    Equivalence Classes:
        -Valid month
            -Input: January, February, ... , December
        
        -Not a valid month but still a string
            -Input: Wisconsin, 25, Bilbo Baggins
    """
    def isolateDatasetByMonth(month):
        """
            Pairs current dataset down by the given month (ie. the data only for March, May, or/and October)

            Retrieves all columns in the current working dataset 
            for each state that containing the given month.

            Args:
                month: an integer indicating the specified month(It must be written in the format of month + year, 
                with no non-numeric symbols in between. For example: 2021/1: 012021; 2020/12: 122020)

            Returns:
                A list of data that contains all of the cells that correspond to the specified month.

        """
        monthDictionary = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June',
                7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}
                
        if month not in monthDictionary.keys():
            print("Not a valid month. Please enter an integer from 1-12 (inclusive)")
            return 0

        print("The database has be paired down to only include", monthDictionary[month])

        return 0    

    """
    Equivalence Classes:
        -Valid category of production
            -Input: 
        
        -Not a valid category but still a string
            -Input: Wisconsin, 25, Bilbo Baggins
    """
    def isolateDatasetByCategoryOfProduction(categoryOfProduction):
        '''
            Pairs data down to just a single category of production 

            Retrieves all columns in the current working dataset that contain the category of 
            production specified in the parameter

            Args:
                categoryOfProduction: a string indicating a specified category of energy production

            Returns:
                A list of data that contains all of the cells that correspond to the specified month.

        '''

        print("The database has be paired down to only include", categoryOfProduction)

        return 0


    def getTotalEnergyForCategoryOfProduction(categoryOfProduction):
        """Sums energy use across all states and months with a specified category of production

        Retrieves columns in the current working dataset pertaining to the given category of
        production for all states and months

        Args:
            categoryOfProduction: a string indicating a specified category of energy production

        Returns:
            returns an integer indicating the sum of total energy production from the provided energy source

        """

        print("The total energy generated by",
            categoryOfProduction, "was 14 billion KWH")

        return 0


    def getEnergyForState(state):
        """Sums all electricity generation by all catagories in a given state

        Retrieves columns in the current working dataset pertaining to each category of electricity 
        generation for a single state, sums the values in these columns and returns that number

        Args:
            state: a string indicating the specified state (must spell the states name out,
            no abbreviations like MN)

        Returns:
            returns an integer indicating the sum of the total electricity generation for the
            provided state

        """

        print("The total energy generated by", state, "was 14 billion KWH")

        return 0


    def getEnergyForMonth(month):
        """Sums all electricity generation by all catagories in a given month

        Retrieves columns in the current working dataset pertaining to each category of electricity
        generation for each state in a specific month, sums the values in these columns and returns 
        that number

        Args:
            month: an integer indicating the specified month(It must be written in the format of month + year, 
            with no non-numeric symbols in between. For example: 2021/1: 012021; 2020/12: 122020)

        Returns:
            returns an integer indicating the sum of the total electricity generation for the
            provided month

        """
        
        monthDictionary = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June',
                7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

        if month not in monthDictionary.keys():
            print("Not a valid month. Please enter an integer from 1-12 (inclusive)")
            return 0

        print("The total energy generated during", monthDictionary[month], "was 14 billion KWH")

        return 0


    def getRenewableEnergy():
        '''
            Sums and returns the total amount of renewable energy for the current state that the dataset has 
            been "paired down to" 

            Retrieves columns in the current working dataset pertaining to each category of renewable 
            electricity generation for each state in a specific month, sums the values in these columns 
            and returns that number


            Returns:
                returns an integer indicating the sum of the total electricity generation from renewable sources 
                for the current state in the current working dataset

        '''

        print("The total energy generated renewable was 14 billion KWH")

        return 0
    

if __name__ == "__main__":
    energy = EnergyProductionAPI('data/total_energy_production_modified.csv')

    print(energy.energy_production)


